### ISSUE TITLE
minio:RELEASE.2021-05-11T23-27-41Z not found

### ISSUE THREAD

**Issue by gsurrel** [marco-m/concourse-in-a-box#1]
The version mentioned in the compose file doesn't exist anymore. It seems to work fine when using the following version:

    minio:RELEASE.2021-08-05T22-01-19Z

Actually, it may be related, but I have another problem. The step "Optional: point your browser to http://localhost:9000 and login." from the readme doesn't work (I get a redirect to http://localhost:38939/, and "Unable to connect")

**Comment by marco-m** [comment]
Ah. It seems I need another way to pin Minio images or drink the Kool Aid and accept "latest".
Let me have a look.

**Comment by marco-m** [comment]
Fixed both problems in 8feaa26.
Does it work ?

**Comment by gsurrel** [comment]
Yep, it does work. I still don't get everything to work as I want, but now that's my problem :)

Thanks you!
